import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
    container: {
        ...theme.share.container,
        position: 'relative',
    },
    gridContainer: {
        display: 'flex',
        flexWrap: 'nowrap',
        overflow: 'hidden',
        [theme.breakpoints.down('xs')]: {
            flexDirection: 'column',
        },
    },
    imagesContainer: {
        maxWidth: 600,
        maxHeight: 600,
        background: theme.palette.common.black,
        overflow: 'hidden',
        position: 'relative',
        [theme.breakpoints.down('xs')]: {
            // order: 2,
            flexGrow: 1,
        },
    },
    arrowBackButton: {
        position: 'absolute',
        top: 'calc(50% - 15px)',
        left: 20,
        color: theme.palette.grey['800'],
        backgroundColor: theme.palette.common.white,
        borderRadius: '50%',
        fontSize: '30px',
        padding: '2px 2px 2px 9px',
        border: '1px solid',
        borderColor: theme.palette.grey['400'],
        cursor: 'pointer',
        '&:hover': {
            color: theme.palette.primary.main,
            borderColor: theme.palette.primary.main,
        },
    },
    arrowForwardButton: {
        position: 'absolute',
        top: 'calc(50% - 15px)',
        right: 20,
        color: theme.palette.grey['800'],
        backgroundColor: theme.palette.common.white,
        borderRadius: '50%',
        fontSize: '30px',
        padding: '4px 4px 4px 7px',
        border: '1px solid',
        borderColor: theme.palette.grey['400'],
        cursor: 'pointer',
        '&:hover': {
            color: theme.palette.primary.main,
            borderColor: theme.palette.primary.main,
        },
    },
    sliderContainer: {
        position: 'relative',
        zIndex: 10000,
        height: 600,
        width: 600,
        overflow: 'hidden',
    },
    sliderItem: {
        width: '100%',
        height: '100%',
        margin: '0 auto',
    },
    images: {
        display: 'block',
        // width: 'auto',
        // height: 600,
        width: '100%',
        height: '100%',
        [theme.breakpoints.down('xs')]: {
            width: '100%',
            height: '100%',
        },
    },
    infoContainer: {
        width: '100%',
        minWidth: 350,
        position: 'relative!important',
        [theme.breakpoints.down('xs')]: {
            flexGrow: 1,
            width: '100%',
            minWidth: '100%',
            height: '100%',
            minHeight: 300, //73 + 72 + 60 + 60 = 265
            overflow: 'hidden',
        },
    },
    userName: {
        fontWeight: 'bold',
        cursor: 'pointer',
        marginBottom: 16,
    },
    contentText: {
        fontWeight: 'normal',
        cursor: 'default',
    },
    cardHeader: {
        borderBottom: '1px solid',
        borderBottomColor: theme.palette.grey['200'],
        position: 'absolute',
        top: 0,
        left: 0,

        width: '100%',
        zIndex: 100,
        background: 'white',
        // padding: '10px 16px 10px 16px',
        [theme.breakpoints.down('xs')]: {
            display: 'none',
        },
    },
    commentContainer: {
        position: 'absolute',
        top: 73,
        left: 0,
        overflowY: 'scroll',
        height: 'calc(100% - 73px - 60px - 60px)',
        '&::-webkit-scrollbar': {
            display: 'none',
        },
        [theme.breakpoints.down('xs')]: {
            top: 5,
            height: 'calc(100% - 60px - 60px)',
        },
    },
    comment: {
        display: 'flex',
        alignItems: 'flex-start',
    },
    actionContainer: {
        height: 60,
        width: '100%',
        borderTop: '1px solid',
        borderTopColor: theme.palette.grey['200'],
        borderBottom: '1px solid',
        borderBottomColor: theme.palette.grey['200'],
        position: 'absolute',
        zIndex: 101,
        bottom: 60,
        display: 'flex',
        alignItems: 'center',
    },
    inputContainer: {
        height: 60,
        width: '100%',
        // width: 350,
        // borderTop: '1px solid',
        // borderTopColor: theme.palette.grey['200'],
        position: 'absolute',
        zIndex: 101,
        bottom: 0,
        display: 'flex',
        alignItems: 'center',
    },

    input: {
        maxHeight: 58,
        width: '100%',
        outline: 'none',
        border: 'none',
        fontFamily: 'inherit!important',
        fontSize: 14,
        paddingLeft: 16,
        paddingTop: 18,
        resize: 'none',
        '&:placeholder': {
            fontFamily: 'inherit!important',
        },
        display: 'flex',
        flexGrow: 1,
        overflowWrap: 'break-word',
    },
    postButton: {
        textTransform: 'capitalize',
    },
    closeIcon: {
        position: 'absolute',
        right: 5,
        top: 10,
        zIndex: 10000,
        [theme.breakpoints.down('xs')]: {
            top: 0,
            right: 0,
        },
    },
}));
